spring:
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    api:
        security:
            token:
                secret: ${JWT_SECRET:123456}
