spring:
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true

    server:
        error:
            include-stacktrace: never

    api:
        security:
            token:
                secret: ${JWT_SECRET:123456}
